apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  CORS_ORIGINS: {{ .Values.config.corsOrigins | quote }}
  KEYCLOAK_ISSUER: {{ .Values.config.keycloakIssuer | quote }}
  KEYCLOAK_JWKS_URL: {{ .Values.config.keycloakJwksUrl | quote }}
  KEYCLOAK_AUDIENCE: {{ .Values.config.keycloakAudience | quote }}
  KEYCLOAK_ALGORITHM: "RS256"
  PUBLIC_API_URL: {{ .Values.config.apiUrl | quote }}
  SEED_DEMO_DATA: "false"
  VITE_API_URL: {{ .Values.config.apiUrl | quote }}
  VITE_KEYCLOAK_URL: {{ .Values.config.keycloakUrl | quote }}
  VITE_KEYCLOAK_REALM: {{ .Values.config.keycloakRealm | quote }}
  VITE_KEYCLOAK_CLIENT_ID: {{ .Values.config.keycloakClientId | quote }}
